# Generated by Django 3.1.7 on 2021-04-27 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HtmlModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(default='', max_length=100)),
                ('_html', models.TextField(default='', max_length=70000)),
            ],
        ),
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(default='', max_length=20)),
                ('title', models.CharField(default='', max_length=70000)),
                ('price', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=70000)),
                ('ratings', models.JSONField(default={})),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
