# Generated by Django 3.1.7 on 2021-04-27 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crawler_App', '0003_auto_20210427_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='price',
            field=models.CharField(default='', max_length=200),
        ),
    ]
